#!/bin/sh
sleep 5
[ ! -s "/etc/config/passwall" ] && sleep 5
[ ! -s "/etc/config/passwall" ] && sleep 5
[ ! -s "/etc/config/passwall" ] && sleep 5
[ ! -s "/etc/config/passwall" ] && sleep 5
[ ! -s "/etc/config/passwall" ] && sleep 5
[ ! -s "/etc/config/passwall" ] && cp -f /usr/share/passwall/0_default_config /etc/config/passwall

exit 0
