#!/bin/sh
uci set network.lan.gateway="192.168.1.1"
uci commit network
/etc/init.d/network restart


if [ "$( opkg list-installed 2>/dev/null| grep -c "^dnsmasq")" -ne '0' ];then
  uci set dhcp.@dnsmasq[0].cachesize='0'
  uci commit dhcp
  /etc/init.d/dnsmasq restart
fi

echo "0 2 * * * /usr/share/cmzj/openwrt-k_tool.sh update rules" >>/etc/crontabs/root
ln -s /usr/share/cmzj/openwrt-k_tool.sh /bin/openwrt-k
chmod +x /usr/share/cmzj/openwrt-k_tool.sh
uci commit
/etc/init.d/sing-box stop
/etc/init.d/sing-box disable
exit 0
